const actionTypes = {
    CHANGE_ACTIVE_PLACE: "CHANGE_ACTIVE_PLACE",
    SET_AGENDA_PLACES: "SET_AGENDA_PLACES",
    SET_LECTURES: "SET_LECTURES",
    SET_CURRENT_LECTURE: "SET_CURRENT_LECTURE",
    SET_CURRENT_LECTURE_SPEAKERS: "SET_CURRENT_LECTURE_SPEAKERS",
    SET_SPEAKERS: "SET_SPEAKERS",
    SET_CURRENT_SPEAKER: "SET_CURRENT_SPEAKER",
    SET_CURRENT_SPEAKER_LECTURES: "SET_CURRENT_SPEAKER_LECTURES",
    TOGGLE_DRAWER: "TOGGLE_DRAWER",
    UPDATE_DRAWER: "UPDATE_DRAWER",
    AUTH_ERROR: "AUTH_ERROR",
    AUTH_USER: "AUTH_USER",
    SIGN_UP: "SIGN_UP",
    SIGN_IN: "SIGN_IN",
}
export { actionTypes };